[project]
name = "slack-stockbot"
version = "0.1.0"
description = "Slack stock bot using Flask + Alpha Vantage"
authors = ["Nolan <frittsdude@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
  "flask",
  "requests"
]
